on: push
name: Build and Publish
jobs:
  all:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.2'
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: Publish
      if: github.ref == 'refs/heads/master'
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}