name: Publish Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build theme on main
        run: |
          npm run build
          rm -rf /tmp/hugo-base-theme
          mkdir -p /tmp/hugo-base-theme
          cp -r build/** /tmp/hugo-base-theme/
      - name: Prep Release
        run: |
          git config --global user.name 'Matt Gaunt'
          git config --global user.email 'hello@gaunt.dev'
          git checkout -b release
          rm -rf *
          rm -rf .github
          cp -r /tmp/hugo-base-theme/** ./
          ls -l
      - name: Commit theme
        run: |
          git add .
          git commit -am "Automated release"
          git push -f origin release